name: Node.js CI

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up working directory for server
        run: cd server
        working-directory: ./server
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm ci
        working-directory: ./server

      # Start backend
      - name: Start backend
        run: npm start
        working-directory: ./server
